{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "helper.serviceAccountName" . }}
  labels:
    {{- include "helper.labels" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- .Values.commonLabels | nindent 4 }}
    {{- end }}
  annotations: 
    {{- with .Values.commonAnnotations }}
    {{- . | nindent 4 -}}
    {{- end }}
    {{- with .Values.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
{{- end }}
