{{- range $currentName, $v := .Values.extraSecrets }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "helper.fullname" $ }}-{{ $currentName }}
  labels:
    {{- include "helper.labels" $ | nindent 4 }}
    {{- if $.Values.commonLabels }}
    {{- $.Values.commonLabels | nindent 4 }}
    {{- end }}
data:
  {{- range $key, $value := $v }}
  {{ $key }}: {{ $value | b64enc |quote }}
  {{- end }}
{{- end -}}