{{- $currentName := "adminer" -}}
{{- $currentValues := get .Values $currentName -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "helper.fullname" $ }}-{{ $currentName }}-env
  labels:
    {{- include "helper.labels" $ | nindent 4 }}
    {{- with .Values.commonLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- with .Values.commonAnnotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
data:
  ADMINER_PLUGINS: {{ $currentValues.plugins | quote }}
  ADMINER_DESIGN: {{ $currentValues.design | quote }}
  