{{- $currentName := "adminer" -}}

{{- $currentValues := get .Values $currentName -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "helper.fullname" . }}-{{ $currentName }}
  labels:
    {{- include "helper.labels" . | nindent 4 }}
    {{- with .Values.commonLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- with $currentValues.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    app.kubernetes.io/component: {{ $currentName | quote }}
  annotations:
    {{- with .Values.commonAnnotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- with $currentValues.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  replicas: {{ $currentValues.enabled | ternary 1 0 }}
  {{- with $currentValues.updateStrategy }}
  strategy: 
  {{- toYaml . | nindent 4 }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "helper.selectorLabels" . | nindent 6 }}
      {{- with .Values.commonLabels }}
      {{- toYaml . | nindent 6 }}
      {{- end }}
      {{- with $currentValues.podLabels }}
      {{- toYaml . | nindent 6 }}
      {{- end }}
      app.kubernetes.io/component: {{ $currentName | quote }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/adminer/configmap.yaml") . | sha256sum }}
        {{- with $currentValues.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- with .Values.commonAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "helper.selectorLabels" . | nindent 8 }}
        {{- with .Values.commonLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- with $currentValues.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        app.kubernetes.io/component: {{ $currentName | quote }}
    spec:
      {{- with $currentValues.initContainers }}
      initContainers: {{- toYaml . | nindent 6 }}
      {{- end }}
      {{- with $currentValues.hostAliases }}
      hostAliases: {{- toYaml . | nindent 6 }}
      {{- end }}
      {{- with $currentValues.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if (or .Values.serviceAccount.create .Values.serviceAccount.name) }}
      serviceAccountName: {{ include "helper.serviceAccountName" . }}
      {{- end }}
      {{- with $currentValues.schedulerName }}
      schedulerName: {{ . | quote }} 
      {{- end }}
      {{- with $currentValues.runtimeClassName }}
      runtimeClassName: {{ . | quote }} 
      {{- end }}
      {{- with $currentValues.priorityClassName }}
      priorityClassName: {{ . | quote }} 
      {{- end }}
      {{- with $currentValues.topologySpreadConstraints }}
      topologySpreadConstraints:
        {{- toYaml . | nindent 6 }}
      {{- end }}
      {{- with $currentValues.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $currentValues.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $currentValues.tolerations }}
      tolerations:
      {{- toYaml . | nindent 6 }}
      {{- end }}
      {{- with $currentValues.imagePullSecrets }}
      imagePullSecrets:
      {{- toYaml . | nindent 6 }}
      {{- end }}
      enableServiceLinks: {{ $currentValues.enableServiceLinks | toYaml -}}
      {{/*==[ CONTAINERS ]================================*/}}
      containers:
      {{/* start new container */}}
      {{- $currentContainerName := "adminer" -}}
      {{- $currentContainerValues := get $currentValues $currentContainerName -}}
      - name: {{ $currentContainerName }}
        image: "{{ $currentContainerValues.image.repository }}:{{ $currentContainerValues.image.tag | default "latest" }}"
        imagePullPolicy: {{ $currentContainerValues.image.pullPolicy }}
        {{- with $currentContainerValues.command }}
        command:
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- with $currentContainerValues.args }}
        args:
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- if $currentContainerValues.tty }}
        tty: true
        {{- end }}
        env:
        {{- with $currentContainerValues.extraEnvVars }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        envFrom:
        - configMapRef:
            name: {{ include "helper.fullname" $ }}-{{ $currentName }}-env
        {{- with $currentContainerValues.extraEnvFromVars }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        {{- with $currentContainerValues.extraPorts }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- with $currentContainerValues.securityContext }}
        securityContext:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with $currentContainerValues.livenessProbe }}
        livenessProbe:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with $currentContainerValues.readinessProbe }}
        readinessProbe:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with $currentContainerValues.resources }}
        resources:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        volumeMounts:
        {{- with $currentContainerValues.extraVolumeMounts }}
        {{- toYaml . | nindent 8 }}
        {{- end -}}
      {{/* end container */}}
      {{- with $currentValues.sidecars }}
        {{- toYaml . | nindent 6 }}
      {{- end }}
      volumes:
      {{- with $currentValues.extraVolumes }}
      {{- toYaml . | nindent 6 }}
      {{- end }}
      
