{{- $currentName := "maildev" -}}

{{- $currentValues := get .Values $currentName -}}
{{- $currentConfig := get $currentValues "config" -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "helper.fullname" $ }}-{{ $currentName }}-env
  labels:
    {{- include "helper.labels" $ | nindent 4 }}
    {{- with .Values.commonLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- with .Values.commonAnnotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
data:
  MAILDEV_WEB_PASS: {{ $currentConfig.http.pass | b64enc | quote }}
  MAILDEV_INCOMING_PASS: {{ $currentConfig.smtp.pass | b64enc | quote }}
  MAILDEV_OUTGOING_PASS: {{ $currentConfig.relay.pass | b64enc | quote }}