##============================================================================= 
## Common Parameters
##=============================================================================

## String to partially override common.names.fullname template (will maintain the release name)
nameOverride: ""

## String to fully override common.names.fullname template with a string
fullnameOverride: ""

## Annotations to add to all deployed objects
commonAnnotations: {}
#   mycommonannotation: "global"

## Labels to add to all deployed objects
commonLabels: {}
#   mycommonlabel: "global"

##============================================================================= 
## Extra ressource parameters
##=============================================================================

## Array of extra objects to deploy with the release (evaluated as a template).
extraResources: []
#- |
#    apiVersion: v1
#    kind: ConfigMap
#    metadata:
#      name: {{ include "helper.fullname" . }}
#    data:
#      test: "true"

extraConfigMaps: {}
#  # ConfigMap name
#  main:
#    # Data keys
#    key: value
#    key2: value2

extraSecrets: {}
#  # Secret name
#  main:
#    # Data keys
#    key: value
#    key2: value2

##============================================================================= 
## Ressource specific parameters
##=============================================================================
  
#---{ Deployment backend }-----------------------
mailhog:
  config:
    smtp:
      # Hostname to use for EHLO/HELO and message IDs
      hostname: "mailhog.example"

    http:
      # URI under which the UI is served, e.g. 'mailhog'
      uri: ""

      # Add a user to enable HTTP Basic authentication
      # each user can be defined as user+clearPassword 
      # or directly a line in htpasswd format
      # Advice : Prefer htpasswd format when possible
      authUsers: []
      #- htpasswd: "test:$2a$04$qxRo.ftFoNep7ld/5jfKtuBTnGqff/fZVyj53mUC5sVf9dtDLAi/S"
      #- user: myuser
      #  clearPassword: "Ch4ngeM3!"

    # Relay section contains one or more smtp relay servers 
    relay: {}
    #  # Server identifier
    #  myserver: 
    #    # [mandatory] Common server name 
    #    name: "My Server"
    #    # [mandatory] SMTP Relay host
    #    host: "smtp.example.com"
    #    # [mandatory] SMTP Relay port
    #    port: "587"
    #    # [optionnal] Envelope From email
    #    email: "test@example.com"
    #    # [optionnal] Authentication mecanism (PLAIN or CRAM-MD5)
    #    mechanism: "PLAIN"
    #    # [optionnal] Authentication username
    #    username: "myusername"
    #    # [optionnal] Authentication password
    #    password: "Ch4ngeM3!"

  # Deployment extra labels
  labels: {}
  # Deployment extra annotations
  annotations: {}

  # Pod extra labels
  podLabels: {}
  # Pod extra annotations
  podAnnotations: {}

  # MailHog pod cannot be scaled more than one pod
  # Instead of managing replicas, you can enable MailHog pod or not
  # If enabled is set to false, it would mean 0 replicas
  enabled: true

  updateStrategy:
    type: Recreate

  # extra initContainers contains a list of Containers
  # https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/pod-v1/#Container
  initContainers: []
  # - name: myinit
  #   image: busybox
  #   args: ["date"]

  hostAliases: []
  # - ip: "127.0.0.1"
  #   hostnames:
  #   - "foo.local"
  #   - "bar.local"

  imagePullSecrets: []
  # - name: secretName

  # Container mailhog
  mailhog:
    image:
      repository: "mailhog/mailhog"
      tag: "v1.0.1"
      pullPolicy: IfNotPresent
    command: []
    args: []
    tty: false
    extraEnvVars: []
    extraEnvFromVars: []
    ports:
    - name: smtp
      containerPort: 1025
      protocol: TCP
    - name: http
      containerPort: 8025
      protocol: TCP
    extraPorts: []
    securityContext: {}
      # capabilities:
      #   drop:
      #   - ALL
      # readOnlyRootFilesystem: true
      # runAsNonRoot: true
      # runAsUser: 1000
    livenessProbe: {}
      # httpGet:
      #   path: /
      #   port: http
    readinessProbe: {}
      # httpGet:
      #   path: /
      #   port: http
    resources: {} 
      # limits:
      #   cpu: 100m
      #   memory: 128Mi
      # requests:
      #   cpu: 100m
      #   memory: 128Mi  
    extraVolumeMounts: []


  # Sidecars are extra containers that will run in same pod
  sidecars: []
  podSecurityContext: {}
    # fsGroup: 2000
  schedulerName: ""
  enableServiceLinks: false
  runtimeClassName: ""
  priorityClassName: ""
  topologySpreadConstraints: []
  nodeSelector: {}
  # key: value
  tolerations: []
  # - key: "key1"
  #   operator: "Equal"
  #   value: "value1"
  #   effect: "NoSchedule"
  affinity: {}
  extraVolumes: []
  # - name: foo
  #   emptyDir: {}

  service:
    enabled: true
    nameOverride: ""
    type: ClusterIP
    clusterIP: ""
    loadBalancerIP: ""
    ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
    - name: smtp
      port: 25
      targetPort: smtp
      protocol: TCP
    extraPorts: []

  smtpOnlyService:
    enabled: false
    nameOverride: "smtp"
    type: ClusterIP
    clusterIP: ""
    loadBalancerIP: ""
    ports:
    - name: smtp
      port: 25
      targetPort: smtp
      protocol: TCP
    extraPorts: []

  persistence:
    # Enable persistence with PVC
    enabled: true
    existingClaim: ""
    # If not using existingClaim, 
    # will create PVC with following parameters
    accessMode: ReadWriteOnce
    size: 10Gi
    storageClass: ""
    # If resourcePolicyKeep is true, helm will not delete PVC on release uninstall
    resourcePolicyKeep: true

#---{ Common serviceAccount }--------------------
serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""
