apiVersion: v2
name: maildev
description: |
  MailDev is a simple way to test your project's generated email during development, 
  with an easy to use web interface that runs on your machine built on top of Node.js.
type: application
version: 0.0.3
appVersion: "v2.0.2"
